---
# Configuration spécifique pour le groupe des bases de données
db_port: 5432 # Port réseau par défaut pour PostgreSQL.
db_engine: postgresql # Nom du moteur pour l'installation automatisée plus tard.
